const actionTypes = {
  // Menu
  FETCH_DATA: 'menu/FETCH_DATA',
  FETCH_ERROR: 'menu/FETCH_ERROR',
  FETCH_CATEGORY: 'menu/FETCH_CATEGORY',
  FETCH_DATA_WITH_CATEGORY: 'menu/FETCH_DATA_WITH_CATEGORY',
  FETCH_DATA_BY_ID: 'menu/FETCH_DATA_BY_ID',
  // Loader
  FETCH_REQUEST: 'menu/FETCH_REQUEST',
  // Cart
  ADD_TO_CART: 'cart/ADD_TO_CART',
  REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
  INCREMENT_AMOUNT: 'cart/INCREMENT_AMOUNT',
  DECREMENT_AMOUNT: 'cart/DECREMENT_AMOUNT'
};

export default actionTypes;
