const actionTypes = {
  // Menu
  FETCH_DATA: 'menu/FETCH_DATA',
  FETCH_CATEGORY: 'menu/FETCH_CATEGORY',
  FETCH_DATA_WITH_CATEGORY: 'menu/FETCH_DATA_WITH_CATEGORY',
  FETCH_DATA_BY_ID: 'menu/FETCH_DATA_BY_ID',
  // Loader
  FETCH_REQUEST: 'menu/FETCH_REQUEST',
  FETCH_ERROR: 'menu/FETCH_ERROR',
  // Cart
  ADD_TO_CART: 'cart/ADD_TO_CART',
  REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
  INCREMENT_AMOUNT: 'cart/INCREMENT_AMOUNT',
  DECREMENT_AMOUNT: 'cart/DECREMENT_AMOUNT',
  // Auth: Sign Up
  SIGN_UP_REQUEST: 'session/SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'session/SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'session/SIGN_UP_ERROR',
  // Auth: Sign In
  SIGN_IN_REQUEST: 'session/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'session/SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'session/SIGN_IN_ERROR',
  // Auth: Sign Out
  SIGN_OUT_REQUEST: 'session/SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'session/SIGN_OUT_SUCCESS',
  // Auth: Refresh
  REFRESH_CURRENT_USER_START: 'session/REFRESH_CURRENT_USER_START',
  REFRESH_CURRENT_USER_SUCCESS: 'session/REFRESH_CURRENT_USER_SUCCESS'
};

export default actionTypes;
